---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Copy the file
     copy:
      src: /tmp/abcd2
      dest: /tmp
      owner: unixadm
      group: root
      mode: 0777
     when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
